### ISSUE TITLE
Front-end styles in a plugin?

### ISSUE THREAD

**Issue by samikeijonen** [10up/plugin-scaffold#73]
I'm probably missing something but why are we using front-end styles like `normalize.css` from the plugin? For all use cases I can think of these should be in a theme only.

**Comment by timwright12** [comment]
Is there a reason we wouldn't include normalize if we're making something like an admin-side plugin? Maybe it's in WP already. I think it's in there just because of the theme/plugin repo syncing. But if there's a reason, we can certainly remove it or just leave that up to the individual project team.

**Comment by samikeijonen** [comment]
I thought it was in the front-end, sorry. I can check later just in case before closing.

**Comment by samikeijonen** [comment]
There is [two files added in the front-end](https://github.com/10up/plugin-scaffold/blob/master/includes/functions/core.php#L184). 

In `tenup_scaffold_frontend ` [normalize.css is coming to front-end](https://github.com/10up/plugin-scaffold/blob/master/assets/css/frontend/style.css#L6). 

I don't think we should duplicate these base styles from the plugin since they already come from a theme. Same goes with [styles in base folder](https://github.com/10up/plugin-scaffold/tree/master/assets/css/frontend/base).

**Comment by samikeijonen** [comment]
@timwright12 There is PR in #78.
